import { Be_Vietnam_Pro, Noto_Sans } from "next/font/google";
import "./globals.css";
import RootClientWrapper from "@/components/RootClientWrapper";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  variable: "--font-be-vietnam",
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-noto-sans",
});

export const metadata = {
  title: "CineBook",
  description: "Generated by Puvanakopis",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${beVietnamPro.variable} ${notoSans.variable}`}>
        {children}
        <RootClientWrapper />
      </body>
    </html>
  );
}