import { Be_Vietnam_Pro, Noto_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CineBotChat from "@/components/CineBotChat"; 

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  variable: "--font-be-vietnam",
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-noto-sans",
});

export const metadata = {
  title: "CineBook",
  description: "Generated by Puvanakopis",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link 
          rel="stylesheet" 
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1" 
        />
      </head>
      <body className={`${beVietnamPro.variable} ${notoSans.variable}`}>
        <Navbar />
        {children}
        <Footer />

        <CineBotChat />
      </body>
    </html>
  );
}